// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1JMUrQ1dyCwBq3b4tZ48XpsEOR5Hh1DQ',
    appId: '1:82299359358:android:d106e3713bf110e9a0c82f',
    messagingSenderId: '82299359358',
    projectId: 'app2-bea90',
    storageBucket: 'app2-bea90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFXjvv7abh2NRUvLK3qY2pISI6LKL65eo',
    appId: '1:82299359358:ios:0ccfefdf1d8e6d49a0c82f',
    messagingSenderId: '82299359358',
    projectId: 'app2-bea90',
    storageBucket: 'app2-bea90.appspot.com',
    iosClientId: '82299359358-kh2jjjf4b7u7qqf3n34lhu32ag6bk5da.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
